### ISSUE TITLE
Create react boiler plate

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#2]
NB: This is not a project centred around building react from scratch. So npx create-react-app is allowed

**Comment by blossom-babs** [comment]
Can I work on this? @joshtom

**Comment by joshtom** [comment]
> Can I work on this? @joshtom

Please feel free to work on it. Expecting your PR 😄

**Comment by femakin** [comment]
Sir! Can I still work on this?😊

**Comment by joshtom** [comment]
> Sir! Can I still work on this?

@blossom-babs has already been assigned to this. Please kindly look into another issue that you can work on.
