### ISSUE TITLE
Create Assets folder

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#21]
This Assets folder should be created in src folder. This is where all the images and logo will live

**Comment by SMAKSS** [comment]
Is this only a folder creation, or some files need to move into it also? Because currently, I can't see any images or logo in the project.

**Comment by Tailine** [comment]
Hi @joshtom I would like to work on it. If I understood correctly this issue is just for creating a assets folder? Do I need to add any images or logos in it?

**Comment by joshtom** [comment]
Hi @Tailine So sorry for the late response, You are very correct. You can create another directory in the assets the folder which would be images and logos. That's all. Expecting your PR :)

**Comment by Tailine** [comment]
@joshtom Ok, can you assign it to me?

**Comment by joshtom** [comment]
Fine. Done!
