### ISSUE TITLE
Set up error 404 page

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#23]
Two things are in place here
- Design the UI for the 404 page
- Any invalid route should lead to the page

**Comment by shubheshdwivedi** [comment]
Can I work on this?

**Comment by joshtom** [comment]
Hello @shubheshdwivedi Please feel free to work on it.

**Comment by shubheshdwivedi** [comment]
Thanks

**Comment by shubheshdwivedi** [comment]
![Capture](https://user-images.githubusercontent.com/20144724/95652803-6ca47980-0b11-11eb-8b25-1b8b98b226d8.PNG)
This is the design I want to implement for 404 page. I am planning to show a random quote on being lost every time you hit a 404.

**Comment by joshtom** [comment]
Wow, this is awesome. Expecting your PR
