### ISSUE TITLE
Improve on Readme

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#35]
This improvement includes
- The package installed in this project
- Essential details on the folder structure
- Best practises to obey when contributing,
**NB**
```
Some useful commands too will be helpful
```

**Comment by Ojay-dev** [comment]
Hello Chief @joshtom , I would like to contribute on this

**Comment by joshtom** [comment]
Hello @Ojay-dev You are free to contribute. Will assign it to you now
