### ISSUE TITLE
Make all the pages responsive

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#37]
Those pages should be accessible to users on mobile or tablet

**Comment by abdulsamad** [comment]
All components in the pages folder should be responsive. Right?
Shall I give this a try?

**Comment by joshtom** [comment]
Hi @abdulsamad yeah you can give it a try. Expecting your PR

**Comment by abdulsamad** [comment]
Sure

**Comment by abdulsamad** [comment]
![React App (2)](https://user-images.githubusercontent.com/38286890/96306343-1f4a6f80-101d-11eb-9afe-cf25b6a5b435.png)
![React App (1)](https://user-images.githubusercontent.com/38286890/96306348-1fe30600-101d-11eb-84ce-5f76fef56e4d.png)
![React App](https://user-images.githubusercontent.com/38286890/96306349-207b9c80-101d-11eb-8f47-af987394223e.png)

@joshtom What do you think?
The background image on the 404 page is not properly visible on all sizes what should I do? Any suggestion?

**Comment by joshtom** [comment]
Hi @abdulsamad You have done a great Job. Well appreciated.

Also, Probably the image is the problem. You can try and get another similar image that gets the issue resolved. Or what do you think?

**Comment by abdulsamad** [comment]
![React App](https://user-images.githubusercontent.com/38286890/96311491-355d2d80-1027-11eb-9fe0-6437270ef2a5.png)
@joshtom 
I think this will probably look fine in most scenarios
The image is below the card separately

**Comment by abdulsamad** [comment]
The image is below the card separately

**Comment by joshtom** [comment]
Okay, This is nice. Anticipating for your PR!
