### ISSUE TITLE
create redux folder in the src directory

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#5]
This redux folder should include subfolders which include

- actions
- actionTypes AND
- reducers

And files which are 
- rootReducer AND
- store.js

**Comment by joshtom** [comment]
Working on this

**Comment by aldo-rl** [comment]
Hi.
Checking the other issues I see that the issue of leaving redux working is separated in various issues. In this issue, will only the folders and empty files be created?

Does this issue carry the installation of redux?

**Comment by aldo-rl** [comment]
I would like to work with issues #3, #5 & #6  so that redux is completely ready and someone else does issue #4.

**Comment by joshtom** [comment]
> Hi.
> Checking the other issues I see that the issue of leaving redux working is separated in various issues. In this issue, will only the folders and empty files be created?
> 
> Does this issue carry the installation of redux?

Yeah, It does

> I would like to work with issues #3, #5 & #6 so that redux is completely ready and someone else does issue #4.

Hello @aldo-rl Sorry for the late response. I have already merged your PR. Do well to notify me if you want to work on more. Keep up the great work!

**Comment by joshtom** [comment]
Also, In the PR you raised, I saw that you have set up the redux structure, You can go ahead with the installation.

**Comment by joshtom** [comment]
The installation has been done by someone else. Thank you for your contribution once again. I will be closing this now.
