### ISSUE TITLE
Create Counter component

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#7]
Must be in ***components*** folder inside src

**Comment by Tailine** [comment]
Hi @joshtom I would like to work on it. How this counter should look like? Also, should this be a class component or a functional component? Should I manage the state using redux?

**Comment by joshtom** [comment]
It's no problem @Tailine . You can check out how the counter should look like [HERE](https://github.com/joshtom/react-redux-starter-template/issues/8), Also, It should be a functional component. There is already an issue for a class component. And YES! Manage the state using redux.

**Comment by Tailine** [comment]
@joshtom So, since the UI is being done I should create the component with the logic?

**Comment by joshtom** [comment]
Hello @Tailine Sadly the UI hasn't been done. The person assigned to it hasn't sent a PR yet. Probably I will just have to do it myself

**Comment by Tailine** [comment]
@joshtom Can I go ahead and work on the logic?

**Comment by joshtom** [comment]
Yeah. Please do. You can try to create a dummy UI just to test. The UI can then be updated later

**Comment by joshtom** [comment]
Welldon @Tailine

**Comment by Tailine** [comment]
@joshtom Awesome. Please assign it to me.

**Comment by joshtom** [comment]
I have done that already

**Comment by joshtom** [comment]
Hello @Tailine, If you are still available to work on this, I have created the counter UI. Just paste it into your own app component then add logic. Thanks.

**Comment by Tailine** [comment]
@joshtom Sure, no problem

**Comment by Tailine** [comment]
Hi @joshtom, I've updated the component with the layout and also create the route to this component. If I understood correctly the interaction is not part of thi issue, am I right?

**Comment by joshtom** [comment]
Great work @Tailine. Interaction is not part, I forgot to add it, please include it in your code.

**Comment by Devdre1909** [comment]
@joshtom

**Comment by Tailine** [comment]
@joshtom Sure, I will work on it today.

**Comment by joshtom** [comment]
Hello @Tailine thank you for finding time out of your busy schedule to contribute. Will review your PR and merge!

**Comment by Tailine** [comment]
Thanks @joshtom, happy to help!
