### ISSUE TITLE
Create UI for the counter app

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#8]
### The Counter app UI should be as simple as this
![image](https://user-images.githubusercontent.com/42160061/95472263-b7d85400-097a-11eb-8e62-aac22222f09e.png)
- Inspiration gotten from
https://dribbble.com/shots/5639404-Stepper-XVIII?utm_source=Clipboard_Shot&utm_campaign=Volorf&utm_content=Stepper%20XVIII&utm_medium=Social_Share

**Comment by blossom-babs** [comment]
I am working on this @joshtom
