### ISSUE TITLE
Add interaction to the Counter app

### ISSUE THREAD

**Issue by joshtom** [joshtom/react-redux-starter-template#9]
### In the Counter app, interactions should be added using redux hooks i.e
- #### useSelector AND 
- #### useDispatch

**Comment by Devdre1909** [comment]
Kindly assign me to this @joshtom, so I can get started when the UI is ready.

**Comment by joshtom** [comment]
Hello @Devdre1909. Thank you for contributing in advance

**Comment by joshtom** [comment]
Hello @Devdre1909 The Counter UI has been created. If you are still available to work on this please go ahead. But it should be a class component. Thank you.

**Comment by Devdre1909** [comment]
Okay, @joshtom Thanks for the update. 
But, I can't use useSelector and useDispatch in class components as required by the issue.

**Comment by joshtom** [comment]
Yeah, This issue addresses using a functional component though. You can wait alongside @Tailine  in this [issue 7](https://github.com/joshtom/react-redux-starter-template/issues/7) if she can implement the UI in a class component. THanks

**Comment by joshtom** [comment]
I will be closing this issue now. Thanks once again.
